name: gradle build

on:
  workflow_call:
    inputs:
      gradle-version:
        description: 'Gradle version'
        required: true
        type: string
        default: '7.2'
      gradle-args:
        description: 'Gradle arguments'
        required: false
        type: string
        default: 'build'
      runs-on:
        description: 'Runs on'
        type: string
        default: 'ubuntu-latest'
        required: false

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
    - name: Set up Gradle ${{ inputs.gradle-version }}
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: ${{ inputs.gradle-version }}
    - name: Build with Gradle ${{ inputs.gradle-version }}
      run: |
        ./gradlew ${{ inputs.gradle-args }}
