# Docker image action
# Composite action (custom one similar to the above)
# Reusable worflow (a whole job)

# Bunch of composite actions can be merged into a one reusable workflow
# Team can use reusable workflow
# Team can use reusable workflow and add some custom jobs w/ composite actions

name: hello

on: [push]

jobs:

  build-gradle:
    uses: Dimpison/github-actions/.github/workflows/build-sample.yml@main
    with:
      gradle-args: 'version'
      gradle-version: '8.8'

  custom-build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failure }}
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 11, 17 ]
        allow-failure: [false]
        include:
          - java-version: 29
            allow-failure: true

    if: ${{ github.ref == 'refs/heads/main' }}

    env:
      ARTIFACT_FILE: my-file-${{ matrix.java-version }}.txt

    steps:
    - uses: actions/checkout@v2

    - name: Check env
      run: env

    - uses: actions/setup-java@v1
      with:
          java-version: ${{ matrix.java-version }}
          java-package: jdk

    - name: Check java version
      run: |
        java -version

    - name: print var
      env:
        TEST: "Hello World"
      run: |
        echo $TEST >> ${{ env.ARTIFACT_FILE }}
        echo ${{ env.GITHUB_ACTOR }} >> ${{ env.ARTIFACT_FILE }}

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_FILE }}
        path: ${{ env.ARTIFACT_FILE }}

  test:
    needs: custom-build

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failure }}
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 11, 17 ]
        allow-failure: [false]
        include:
          - java-version: 29
            allow-failure: true

    env:
      ARTIFACT_FILE: my-file-${{ matrix.java-version }}.txt

    steps:
    - uses: actions/checkout@v2

    - name: download artifact
      if: ${{ ! github.ref == 'refs/heads/main' }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.ARTIFACT_FILE }}

    - name: print artifact
      if: ${{ ! github.ref == 'refs/heads/main' }}
      run: |
        cat ${{ env.ARTIFACT_FILE }}
        
