name: hello

on: [push]

env:
  RELEASE_BRANCH: main

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failure }}
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 11, 17 ]
        allow-failure: [false]
        include:
          - java-version: 29
            allow-failure: true

    if: ${{ github.ref == env.RELEASE_BRANCH }}

    env:
      ARTIFACT_FILE: my-file-${{ matrix.java-version }}.txt

    steps:
    - uses: actions/checkout@v2

    - name: Check env
      run: exit 1

    - uses: actions/setup-java@v1
      with:
          java-version: ${{ matrix.java-version }}
          java-package: jdk

    - name: Check java version
      run: |
        java -version

    - name: print var
      env:
        TEST: "Hello World"
      run: |
        echo $TEST >> ${{ env.ARTIFACT_FILE }}
        echo ${{ env.GITHUB_ACTOR }} >> ${{ env.ARTIFACT_FILE }}

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_FILE }}
        path: ${{ env.ARTIFACT_FILE }}

  test:
    needs: build

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failure }}
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 11, 17 ]
        allow-failure: [false]
        include:
          - java-version: 29
            allow-failure: true

    env:
      ARTIFACT_FILE: my-file-${{ matrix.java-version }}.txt

    steps:
    - uses: actions/checkout@v2

    - name: download artifact
      if: ${{ ! github.ref == env.RELEASE_BRANCH }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.ARTIFACT_FILE }}

    - name: print artifact
      if: ${{ ! github.ref == env.RELEASE_BRANCH }}
      run: |
        cat ${{ env.ARTIFACT_FILE }}
        
