name: hello

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 11, 17 ]
        allow-failure: [false]
        include:
          - java-version: 29
            experimental: true
    continue-on-error: ${{ matrix.allow-failure }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check env
      run: env | sort

    - uses: actions/setup-java@v1
      with:
          java-version: ${{ matrix.java-version }}
          java-package: jdk

    - name: Check java version
      run: |
        java -version

    - name: print var
      env:
        TEST: "Hello World"
      run: |
        echo $TEST >> artifact_file.txt
        echo ${{ env.GITHUB_USER }} >> artifact_file.txt

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: artifact_file.txt

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: download artifact
      uses: actions/download-artifact@v4
      with:
        name: artifact

    - name: print artifact
      run: |
        cat artifact_file.txt
        
